AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sunpower-get-data

  SAM application that authentications and retrieves energy data from a customer's sunpower account

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    
Resources:
  EnergyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: energy/
      Handler: app.lambda_handler
      Runtime: ruby2.5
      Environment:
        Variables:
          HELLO: "world"
          LOGLEVEL: 1
      Policies: 
        - SSMParameterReadPolicy: {
          ParameterName: "sunpower-username",
        }
        - SSMParameterReadPolicy: {
          ParameterName: "sunpower-p",
        }
        - SQSSendMessagePolicy: {
          QueueName: "sunpower-energy-queue"
        }
        - Version: "2012-10-17"
          Statement:
            Effect: "Allow"
            Action:
            - "sqs:GetQueueUrl"
            Resource: '*'
      Events:
        DailyEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 6 * * ? *)
            
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EnergyFunction:
    Description: "Energy Lambda Function ARN"
    Value: !GetAtt EnergyFunction.Arn
  EnergyFunctionIamRole:
    Description: "Implicit IAM Role created for Energy function"
    Value: !GetAtt EnergyFunctionRole.Arn